# Generated by Django 5.1.1 on 2024-10-19 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('city', models.CharField(max_length=100)),
                ('school_name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('junior', 'Junior'), ('senior', 'Senior'), ('elementary', 'Elementary')], max_length=20)),
            ],
        ),
    ]
