# Generated by Django 5.1.1 on 2024-10-19 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_check'),
    ]

    operations = [
        migrations.DeleteModel(
            name='check',
        ),
    ]
