# Generated by Django 5.1.1 on 2024-12-30 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_delete_check'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='category',
            field=models.CharField(choices=[('junior', 'Junior'), ('senior', 'Senior'), ('elementary', 'Elementary'), ('lightweight', 'Lightweight'), ('lfr', 'LFR (Modular)')], max_length=20),
        ),
    ]
